### ISSUE TITLE
Update relationships after destroy entity

### ISSUE THREAD

**Issue by valikos** [dixieio/redux-json-api#104]
Found issue with `makeUpdateReverseRelationship` function.
I've got undefined `newRelation` after delete entity with relations.
I checked what compiled sources I have in node_modules and I have
```
  var newRelation = arguments.length <= 2 || arguments[2] === undefined ? {
    type: resource.type,
    id: resource.id
  } : arguments[2];
```
I compiled source from `state-mutation.js` in `babeljs.io` console. There is another result
```
  var newRelation = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {
    type: resource.type,
    id: resource.id
  };
```
I am using latest `react-modules` package where `babel` and related things are preinstalled. 
Can't understand how to figure out there.

**Comment by valikos** [comment]
I played a bit with this issue and found what works for me.
When I do a call `makeUpdateReverseRelationship(resource, resource.relationships[key], 'delete')` instead `makeUpdateReverseRelationship(resource, resource.relationships[key], null)` this is working for me and relations updates well.

**Comment by valikos** [comment]
Actually there is enough remove third `null` parameter from call of `makeUpdateReverseRelationship`. 
Is there a reason to call `makeUpdateReverseRelationship` in removeEntity with `null` third parameter when relations is not defined for entity?

**Comment by egeriis** [comment]
So the issue is that you're getting a reverse relationship updated to `undefined` after deleting an entity? Can you maybe write a failing test for this in a PR? :)

**Comment by valikos** [comment]
@egeriis ok, I will try write failing test

**Comment by valikos** [comment]
@egeriis I've create PR with broken test for my situation https://github.com/dixieio/redux-json-api/pull/107

**Comment by valikos** [comment]
I am using one-to-many relation for my resources.
One resource returns multiple relationships with links and data for resources that related to parent scope. Similar to article and comments, project and tasks. 
And related resources contains single relationship with data.
I think this is allowed by jsonapi convention.
