### ISSUE TITLE
Thoughts on posting child objects to the createEntity method

### ISSUE THREAD

**Issue by tomharvey** [dixieio/redux-json-api#111]
Let's say I have a cart, which is stored as a list of line items in my state: 

```
state.cartItems:
[
  {productId: 1, quantity: 2},
  {productId:2, quantity: 2}
]
```

I have a form which collects the customer name and on the backend I have an API server ready to create orders with line_items as child objects.

This form could either make one `POST /orders` with the customer's name and retrieve a newly created order ID. Then it would make a `POST /line-items` for each item in the cart, adding `orderId` to the existing `productId` and `quantity` keys of these items to create the child objects.

Or, I'm thinking preferable, it would make a single `POST /orders` with the line items in the body of the request, somewhere...

When posting a single object, it would be my understanding of the JSON-API spec that the below would be the valid approach:

``` json
{
    "data": {
        "type": "orders",
        "attributes": {
            "customer_name": "Bob",
        }
    },
    "included": [
        {
            "type": "line_items",
            "attributes": {
                "product_id": 1,
                "quantity": 1
            }
        },
        {
            "type": "line_items",
            "attributes": {
                "product_id": 1,
                "quantity": 1
            }
        }
    ]
}
```

However, I can't make that request using this library. In the meantime I've settled for including the actual child attributes in the `relationships` object of the parent, as opposed to just the IDs (which don't yet exist). As below:

``` json
{
    "data": {
        "type": "orders",
        "attributes": {
            "customer_name": "Bob",
        },
        "relationships": {
            "line_items": {
                "data": [
                    {
                        "type": "line_items",
                        "attributes": {
                            "product_id": 1,
                            "quantity": 1
                        }
                    },
                    {
                        "type": "line_items",
                        "attributes": {
                            "product_id": 2,
                            "quantity": 3
                        }
                    }
                ]
            }
        }
    }
}
```

Given that I have a  work around for now, it's far from urgent. But, it doesn't seem like it would be too difficult to include a `{included: cartItems}` option to the `createEntity` method and I was wondering what your thoughts were on whether or not the approach above is actually valid JSON-API or if you've a preferred way to approach this?

**Comment by egeriis** [comment]
This is something that we are looking to get fixed too. We just haven't gotten to it.

Our approach currently it to create the parent first, then create the resources that "belongs-to" that parent. Because creating the parent first would respond with an ID to reference in relationships for the child resources.

While I think you're right that your first JSON snippet would be a valid request body, JSON API spec doesn't state what to do with the `included` resources: http://jsonapi.org/format/#crud-creating

Bulk creation was previously a part of their extensions section, but never materialized as a core part of JSON API nor a common extension. 

I am unsure what to do about this, as there are no specification for bulk creation. What are your thoughts @tomharvey?

**Comment by tomharvey** [comment]
Thanks! Yes, I struggled to find clarity in the JSON API spec for the kind of creation I described above myself. Is it your understanding that my second snippet for bulk creation (which I'm using) is invalid; including more than just the relationship IDs in the relationship data objects?

The many calls approach certainly seems like the most dogmatically correct approach but I'm concerned about the performance hit, but also in splitting up the DB write into many transactions.

I might have a look through https://github.com/json-api/json-api to see if there is any discussion over there, otherwise great to your thoughts as/if they progress. Not sure if this would constitute an open issue in your repo policy either.

**Comment by egeriis** [comment]
I don't feel like I am able to conclude anything, because the spec doesn't mention it. So I wouldn't say that any approach is wrong, I'd rather point out that there are no _right_ solution atm.

**Comment by tomharvey** [comment]
Having trawled through more of the JSON API spec it looks like they haven't any official way to accomplish what I'm suggesting, but as you say, they don't have any strict opposition to doing it.

https://github.com/json-api/json-api/issues/795#issuecomment-159926461 shows a proposal similar to the 'workaround' I'm using above and that seems to be one solution being considered.

I'll close this off; definitely no point in working on a solution in here while the spec doesn't have an agreed approach. Hopefully this will provide some future explorer some comfort tho... Thanks
