### ISSUE TITLE
Possible to read response meta?

### ISSUE THREAD

**Issue by ryantownsend** [dixieio/redux-json-api#121]
[jsonapi-resources](https://github.com/cerebris/jsonapi-resources), a popular Rails library for building JSONAPI-complaint APIs, utilises `meta` for things like pagination counts.

I can't seem to find anything pertaining to `meta` in this library whatsoever. Does anyone have any recommendations for how I could access it?

**Comment by Kou-Guandong** [comment]
I've got the same problem, and struggled to find a solution. I don't think it is the best way to write a separate action/reducer by hand.

**Comment by egeriis** [comment]
You can read the response from the resolve callback, i.e. `readEndpoint(...).then(res => console.log(res))` would log the response.

**Comment by ryantownsend** [comment]
Wouldn't this be better as a native part of the library's reducer, rather than something handled inside a component?
