### ISSUE TITLE
Provide option to use objects/maps keyed on ID rather than arrays in the saved state

### ISSUE THREAD

**Issue by dustinstanley** [dixieio/redux-json-api#124]
Hello,

I was trying an example of this library against some JSON-API endpoints and noticed that after a read operation, the redux state looked like it was storing the retrieved entities in arrays (like the following):

`{
	api: {
		entityTypeOne: {
			data: [ {id: 1}, {id: 2}, ...]
		},
		entityTypeTwo: {
			data: [ {id: 1}, {id: 2}, ... ]
		}
	}
}`

Is there an option to instead persist the data in the state such that the "data" properties are actually objects/maps keyed on entity ID rather than simple array similar to what is described in the redux documentation here for state normalization: http://redux.js.org/docs/recipes/reducers/NormalizingStateShape.html

I could write helper functions to find the entity by ID by searching through the arrays, but the object/map approach should perform a lot better and is more convenient.

Is there a way to configure library to store the state like this?

Thanks!

**Comment by Nopzen** [comment]
Hello @dustinstanley 

Thanks for rasing this flag, as of now the short answer is no, the library cant store enteties as keyed objects.

To address this:
>I was trying an example of this library against some JSON-API endpoints and noticed that after a read operation, the redux state looked like it was storing the retrieved entities in arrays.

This is the expected  behaviour according to the spec :)

But i dont see the reason why it can't, but i would like to see the reason behind moving the ID our as a key to the object rather than just loop though the arrays and find the entity needed.

The only plus side i can see is we can save a `forEach`, `find or `findIndex` to find or look for a certain entity rather than just saying `entityType[key]` directly, but it would then remove the convention of the [JSON API](http://jsonapi.org/) spec of having the entity described as so:

```js
{
  id: "1"
  type: "type"
  ... etc
}
```

And i dont like doing this because its the spec this tool is build around so there should be a really nice reason behind this ?

**Comment by dustinstanley** [comment]
I think that aside from the convenience of having things keyed on IDs, the other nice thing about it is that it will perform better whenever you need to look up an object by ID.  Using a helper function, you are looking at O(n) worst case runtime, whereas with a map it'll be closer to constant time on a modern JS engine like V8.

If you have a lot of items in your array, that can be a significant performance improvement.

It seems like a common use case to look up items by ID, so it makes sense that the data in a redux app should be structured in such a way to facilitate that easily.  The redux documentation recommends this in its documentation regarding Normalization of State Shape (see link in my first comment), and this is also how some other normalization libraries do it (https://github.com/paularmstrong/normalizr and https://github.com/yury-dymov/json-api-normalizer are some examples, the second one designed around handling JSON-API formats as well).

In my opinion the state of the redux app should be structured to be convenient for the developers working on the app, and modeling it to more closely mimic the JSON-API payloads (as it is now) makes it less convenient.  I also don't really understand the benefit of doing it this way...I agree that it more closely follows the JSON-API spec but I don't see how having the state shaped this way helps with the development of the redux app itself.  In other words, I think JSON-API is great for transferring of data but once we have the data I'm not seeing the benefits to shaping the state strictly in that format.

I hope this doesn't come across as too critical, as I think you guys have a nice library here.  But this was something that I found lacking when comparing it to other libraries doing similar things.

**Comment by Nopzen** [comment]
Hi @dustinstanley 

I can totally see the bennefit most of the time we know the `id` of an `resource, and it makes it really tedious to run a `Array.find()` or `Array.findIndex` what ever the case should be and i know there could be performance issues on larger scale data sets for sure.

But in my opinion this tool is build to follow as strictly the `json-api` spec to not have any confusions regarding the response from the server and the stored data is the same, and i think this i a really great idea to keep it this way.

Another question could be raised like should this be a option if the users want to option in `storeEntityOnID` kinda thing where the user could then say yes we want to store them like you say, but i also think this is a kinda middleware that could be up to the single user to do them self if they want that for there application specifically. 

So the **_TL;DR_** 
1. As i see it, its between developer sanity and performance
2. Keeping a strict convention with i think is implied when you are already taking the action you want to have a convention on you api's.

Im more in for 2 here an letting people write hooks into this them self, as the structure would always be the same from out side so users can expect the output from this tool :)

I would like to have @egeriis suggestions on this aswell, if possible?

**Comment by Nopzen** [comment]
Closing this issue for the v3.0 Proposal talk ^
