### ISSUE TITLE
Examples in README

### ISSUE THREAD

**Issue by makeitTim** [dixieio/redux-json-api#13]
Hi, thanks for this!

I'm having trouble with the Usage instructions. I've created a store with the included reducer and the initial empty state is loaded (in this case into react). I have not been able to setup the endpoint or use it beyond this. Are there any examples? Even just expand the Usage section in the read me with where and how to use the setup and initial read actions/methods.

I have one more basic question --- JSON-API is not a data structure but describes a data structure. I still have to manually convert JSON-API into props objects easily usable in react components? Any tips on where/how it's best to do that?

**Comment by egeriis** [comment]
Hi @makeitTim,

Thank you for your questions.

It would be easier for us to assist you, if you provided a code example with the state you're at. You say that you have not been able to setup the endpoint, do you mean that you're having trouble getting the host and path set in state?

The practice that we've used to far for binding the API data to views, is through the decorator [mapStateToProps](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options). We're drafting helper methods, that does not require you to do much logic yourself using mapStateToProps, but this is an example implementation:

```js
const mapStateToProps = ({ api: { users } }) => ({ users });
```

This is just a simple map of all users to the `users` prop.

**Comment by makeitTim** [comment]
Thanks for the reply @egeriis 

I've now been able to set the endpoint values in state. At first I thought the setup stuff were methods and the api calls were reducer actions, instead of the opposite? The state exists and has the endpoint entries but I havn't been able to get any api data returned, or get the error messages to work.

This is the code I have, right now just in my index.jsx
```
import {
  reducer, setAccessToken, setEndpointHost, setEndpointPath, readEndpoint
} from 'redux-json-api'
//...
const store = createStore(reducer)

store.dispatch( setEndpointHost('http://antares-api.herokuapp.com') )
store.dispatch( setEndpointPath('/') )
store.dispatch( setAccessToken('') )

readEndpoint('channels', 
  (json) => {
    console.log('readEndpoint SUCCESS')
    console.log(json)
  },
  (err) => {
    console.log('readEndpoint ERROR')
    console.log(err)
  }  
)
//...
```
So `http://antares-api.herokuapp.com/channels` has some json-api data I want. I have no auth. I'm not getting success or error.

**Comment by makeitTim** [comment]
I see how you map the JSON-API to props for the component, with all the extra object levels still included? My API call includes needed associated data which will be in completely different objects instead of correctly nested relationships. Making the JSON-API data a huge mess to work with... JSON-API needs that other step to turn it into usable data?

**Comment by egeriis** [comment]
There's no such thing as a "reducer action" :)

All the methods that are exported by redux-json-api are actions. For actions to be properly executed, you need to dispatch them. So I think, from your example, what you need is to wrap `readEndpoint` in a `dispatch` call :)

-----

It's completely up to you, what data you map to your components. What redux-json-api ensures, is that you have each entity that have been fetched, created or updated, properly up-to-date and stored only in 1 place in the state. That is the main goal.

What we're currently drafting, is some helper methods that will make it easier to fetch a desired sub-set of entities from the state. Say that you have a _users_ entity, which has a relationship to 5 _comments_:

```json
{
  "id": 1,
  "type": "users",
  "attributes": {
    "name": "Tim the King"
  },
  "relationships": {
    "comments": {
      "data": [
        { "id": 1, "type": "comments" },
        { "id": 2, "type": "comments" },
        { "id": 3, "type": "comments" },
        { "id": 4, "type": "comments" },
        { "id": 5, "type": "comments" }
      ]
    }
  }
}
```

While all _users_ are stored in `store.api.users`, the comments are stored in another key on the state, `store.api.comments`.

Then you want to fetch _comments_ with IDs 1 through 5, because that's the ones related to the specified _users_ entity, you could map all _comments_ to the component which needs them and filter the list in a getter.

Another way would be to filter the list in mapStateToProps, which I think would be more appropriate, as there are less data tied up to the component. But this is a bit of a syntactic hassle right now, as I see it:

```js
const mapStateToProps = ({ api: { users, comments } }) => ({
  users,
  comments: comments.data.filter(comment => users.data[0].relationships.comments.findIndex(c => c.data.id === comment.id) > -1)
});
```

This is not readable at all. So we want to make that easier too :) Any input is very welcome.

**Comment by makeitTim** [comment]
`store.dispatch( readEndpoint('channels') )` errors `Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.` which is why I thought readEndpoint() it wasn't meant to be an action. I'm surely missing something.

Regarding the data, it would be awesome to have a built in way to re-structure the data to expected relationships. Take your example, if you requested the list of users it would give you convenient objects for props:
```
"users" : [
  {
    "name": "Tim",
    "comments": [{"id":1, "post":"Hello"}, {"id":1, "post":"Bye"}]
  }, {
   so on....
]
``` 
But I don't know how to efficiently do that in a Redux state. Making it another whole data tree in the state would make multiples of the same data in a horrible messy way like you say. Maybe there is  away to efficiently do it by reference, or only create the data when needed.

In the mean time I'll just map the data as needed in the mapStateToProps container wiring as you suggest, when I get this data going.

**Comment by egeriis** [comment]
I'm not sure such restructuring can be done generic enough to be suitable for implementing into this library.

Maybe we're missing a dependency notation, because I think the error you're receiving is due to missing `redux-thunk`.

**Comment by makeitTim** [comment]
Yeah, @egeriis! That finally did it. I did not redux-thunk. I also needed to combine the redux-api-json reducer to api. I'm not sure if this is just right, but this is what I did to get working:

```
const store = createStore(
  combineReducers({'api' : reducer, myReducer}),
  applyMiddleware(thunk)
)

const host = 'http://my-api.herokuapp.com'
const path = '/'

store.dispatch( setEndpointHost(host) )
store.dispatch( setEndpointPath(path) )

store.dispatch(readEndpoint("channels", {
        onSuccess: (json) => console.log(json),
        onError: (err) => console.error(err)
    }));
```

**Comment by Nopzen** [comment]
Hey @makeitTim

Glad to see you got it to work, regarding getting state to update with the data coming back from your api call's. The trick here is that you bind the reducer from redux-json-api, to you store's combined reducers.

Here's a example that we are running with
```javascript
// rootReducer.js
import { combineReducers } from 'redux';
import { reducer as api } from 'redux-json-api';

export default combinedReducers({api});
```

In your example, the api is tied to reducer:
`combineReducers({'api' : reducer, myReducer})` - __reducer__ must be the one from `redux-json-api` is this the case?

Furthermore i can recommend this tool: Redux DevTools
https://chrome.google.com/webstore/detail/remotedev-devtools/npmkpkaejamnfodceoimeeioacfcijop?hl=da

To test if actions is called and so forth, you will also be able to see what payloads and responds comes from Redux Json Api actions.

But i will agree with you we should proberly make a better documentation for this case.

**Comment by makeitTim** [comment]
Thanks for the reply @Nopzen 

Yes, in that example reducer is imported from redux-json-api. The state.api initial setup works and the state.api.endpoint stuff works. (I have now moved the reducers to separate files like your example). The endpoint call returns json successfully. The state data just isn't updating with the json data.

I do have the Redux Remote DevTools plugin installed... I've seen examples on how to configure the store for it, I was just trying to get the store working at all first. I'll take your advice and get that going next and try to figure out what exactly is going on.

**Comment by makeitTim** [comment]
Okay, it seems I'm no longer getting the json data because the api is now returning `304 Not Modified`.

**Comment by egeriis** [comment]
Hey @makeitTim,

That the API returns 304, should not change anything. Then the browser will grab the response body from cache. This should not affect redux-json-api. But let me verify for a moment, if we've made an error and registered 300+ status codes as errors.

**Comment by egeriis** [comment]
I can see that we've made an error and will throw an error if the status code is 300 or above.

https://github.com/dixieio/redux-json-api/blob/master/src/utils.js#L19

We'll fix that immediately and push an update.

**Comment by egeriis** [comment]
Hey @makeitTim,

I'm not sure this is actually an issue in redux-json-api. The API that we're using, internally, is not responding with 304, so I cannot test the behaviour out of the box.

Can you try to disable the cache in your browser, and see if redux-json-api properly works?

If it works properly, then if you could add a breakpoint here and see if `res.json()` contains the response body? https://github.com/dixieio/redux-json-api/blob/master/src/utils.js#L27

**Comment by makeitTim** [comment]
Cool, thanks @egeriis I appreciate the help...

Yeah, I was wrong in my last post, it still contained the JSON data. This is the whole HTTP response :
```
HTTP/1.1 304 Not Modified
Server: Cowboy
Date: Wed, 27 Apr 2016 15:16:03 GMT
Content-Length: 0
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Etag: W/"c3551db8e597753d918f92c3f05daa2f"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: d9a4b39d-e0b2-4ce1-94c0-251db056277f
X-Runtime: 0.389257
Access-Control-Allow-Origin: http://localhost:4200
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD
Access-Control-Max-Age: 1728000
Access-Control-Allow-Credentials: true
Vary: Origin
Via: 1.1 vegur
```
Even though the Content-Length: 0 the response body does contain all the JSON-API data, structured `{ data: [...], included: [...] } `.

However, where you pointed out in the fetch().then() method of utils.js the response claims to be status: 200 and the res.json() is still a promise.
`res` is `{type: "cors", url: "http://antares-api.herokuapp.com/channels", status: 200, ok: true, statusText: "OK"…}`
`res.json()` is `Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}`

So the response status doesn't match, I don't know if that's a problem. Also the Content-Length: 0 might be a problem too. I'm gonna continue messing with both ends.

Note that the same endpoint as-is works perfectly with an Ember front-end using JSONAPIAdapter.

**Comment by makeitTim** [comment]
I prevented the server from responding with 304, it is now 200 without Content-Length. The same thing happens --- despite the response containing the JSON-API data res.json() is still a promise and the store never updates.

**Comment by makeitTim** [comment]
Okay, I think I've solved it! (And being a promise there makes sense.) The problem was that the fetch() method checks for for only content types 'application/json', 'application/vnd.api+json' specifically, but mine was 'application/vnd.api+json; charset=utf-8'. So it was never returning the correct json. If I allow it, it returns the correct res.json() and the store updates!!

This is the [relevant section of the JSON-API spec](http://jsonapi.org/format/#content-negotiation)... but it it isn't clear about charset. As far as I can tell utf-8 is the default standard for JSON, but it can be anything. So maybe allowing that to be in the header is the way to go.
```
    if (res.status >= 200 && res.status < 300) {    
      if (res.headers.get('Content-Type').indexOf('json') !== -1) {
        return res.json();
      }

      return res;
    }
```
This would return a json() on any content-type involving json, which would catch any malformed old API. Strictly following spec could only check for `'application/vnd.api+json'`

I haven't forked. If you want I could make the change and do a pull. But it's up to you guys how to handle.

This may also be the problem #14 is having.

**Comment by egeriis** [comment]
Haha, I'll be damned. That's a very nice catch, after a lot of digging!

Allow us to fix this tomorrow, we'll push an update. We decided to support both `application/json` and `application/vnd.api+json`, but it may be unnecessary to do so. But we'll surely implement the ability to pass params with the header.

Note: That `Content-Length` is 0, should be fine for cached resources. It just means that the server sent 0 bytes, not that no content was retrieved. But your conclusion regarding 304, was that it worked as intended?

**Comment by makeitTim** [comment]
My api (on rails 5) originally did have `application/json` set as the content-type and I switched it to `application/vnd.api+json` but couldn't immediately figure out how to remove the charset. Up to you guys how strictly the apiRequest method should verify JSON-API, but I tend not to want to rely on perfect headers if the json object itself is usable.

Regarding the 304, I just told the server to disregard Last-Modified and consider all requests as fresh. The 304 responses seemed to include all the data anyways. I'm not sure if it was acting correctly (or really how it was supposed to act). In the long run I'd like the asynchronous data to persist correctly with timely updates so I'll look at it again later on.

**Comment by egeriis** [comment]
It makes sense, if you have a working caching algorithm, to utilize that. What I was interested in hearing, is if the response was properly parsed by redux-json-api with 304 status code and Content-Type without charset?

**Comment by makeitTim** [comment]
Yes... I turned the 304 back on. The response is `HTTP/1.1 304 Not Modified` and includes the json data, and that data loads correctly into the Redux state.api. When `res.status` is checked it is equal to 200, which I think makes sense because the browser just redirects 304 to the cache and calls it a 200 success. So it's as expected.

**Comment by egeriis** [comment]
Great! Thanks for the clarifications.

**Comment by egeriis** [comment]
We've pushed an update (v1.3.5) which should fix this issue. Can you confirm?

**Comment by makeitTim** [comment]
Yep! The data is loading with `Content-Type: application/vnd.api+json; charset=utf-8`.

**Comment by egeriis** [comment]
That's just wonderful. Thank you for helping pointing out this issue.
