### ISSUE TITLE
Cancellable XHRs

### ISSUE THREAD

**Issue by jmeas** [dixieio/redux-json-api#132]
Promises for XHRs are nifty – particularly for control flow (`Promise.all`, etc) – but provide a subset of functionality compared to the xhr object, since they don't support aborting. On the other hand, a fully-functioning Promise can be built pretty simply from a regular xhr object.

It'd be pretty cool if this library supported aborting requests.

One idea for doing this would would be to use a different xhr abstraction than `fetch`, and to provide a way to access the `xhr` object for cancellation. Then, folks can just call `abort.request`. In the xhr callback, you could check for the aborted status, and fire off an abort action creator to update the store.

You could still create and return a Promise, of course, as some option. Perhaps the action type would allow you to specify receiving that (or the other way around, for backwards compatibility, although I think the more powerful tool should be the default). That way, folks that need Promises can use them, and folks that need to abort requests can abort them using the xhr.

**Comment by Nopzen** [comment]
Helle @jmeas 

I can tell you the following, `v2.0.0-beta.0` is currently moving away from the `fetch` lib and moving to [Axios](https://github.com/mzabriskie/axios), im not sure if this is library supports your requested behavior, feel free to dig in to the axios api and see :) and if you find anything come up with a PR :)

I hope this helps you for now, we are always interested in new features :)

**Comment by jmeas** [comment]
Thanks for the response, @Nopzen ! axios does suppotrying cancellation 🙂 I'll close this out

**Comment by Nopzen** [comment]
@jmeas - You're very welcome.
