### ISSUE TITLE
Missing "lib" after npm install, probably because of test failed

### ISSUE THREAD

**Issue by iroy2000** [dixieio/redux-json-api#134]
After npm install, the redux-json-api module is missing the "lib" folder which was defined in the package.json

![screen shot 2017-04-26 at 4 04 24 pm](https://cloud.githubusercontent.com/assets/487520/25460786/3001b9e4-2a9a-11e7-8959-9efa75d35255.png)

And when I check out the project, the test is failed

![screen shot 2017-04-26 at 4 09 11 pm](https://cloud.githubusercontent.com/assets/487520/25460893/caa72466-2a9a-11e7-8534-243dc447a223.png)

Wonder if that's related to #118

**Comment by Nopzen** [comment]
Hi @iroy2000 

I dont think this is releated to the lib missing, if you check out the `2.0` branch this is fixed, we proberly should fix this issue in the 1.x.x aswell, i know all tests got fixed with `2.0`

Also the lib is basicly the build version of the module, so this should not effect the tests, since the tests are executed on files within the `test` folder.

**Comment by iroy2000** [comment]
@Nopzen , I meant the `lib` is missing in the build, I didn't mean the test fail is because of that.  What I meant is actually the reversed, is it because the test fail, that's why the build command is not run ?

**Comment by Nopzen** [comment]
@iroy2000 

Sorry my bad, but no the tests are not blocking the build

build command `"build": "rimraf lib && babel ./src -d lib"` do not trigger the build, the build error is happning on travis, who is only responsible from what i know to run the test seperately.

If the lib is missing it more likely that we have removed the lib, and forgot to build before a release, witch seems very unlikely, but i can see the lib is missing from the repo, and is not `.gitignored`

How dod you install this package, or did you clone the repo ?

**Comment by iroy2000** [comment]
@Nopzen I just run `npm install --save redux-json-api`  ( just like other npm packages )

**Comment by Nopzen** [comment]
@iroy2000 - Let me get back to you later, im currently a bit occupied, but it seems wired. :)

**Comment by iroy2000** [comment]
It turns out it is an issue on my side, closing this ticket.

**Comment by Nopzen** [comment]
Hello @iroy2000 

Sorry i didn get back to you, been very busy, but how did you solve this isse, another user experiences similar issue in `v2.0.0` see #136

**Comment by iroy2000** [comment]
Hi @Nopzen ,

It is still happening, my co-workers telling me it is fine, so I close it, but when I test it today, it is still failing.

**Comment by Nopzen** [comment]
Hi @iroy2000 

Yeah i saw the PR, but personally im pretty swamped right now, maybe @egeriis could take over this one?

I know for at least 1 week or so I wont have the time to devote my full attention span to this, sorry for the delay.

**Comment by Nopzen** [comment]
Hi @iroy2000 

Could you try the new `v2.0.0-beta.2` to see if it got fixed ?

**Comment by Nopzen** [comment]
Closing since bug seems fixed in #136
