### ISSUE TITLE
v2.0.0-beta.1 no lib folder when installing from npm

### ISSUE THREAD

**Issue by aklkv** [dixieio/redux-json-api#136]
I have installed latest beta from npm and there is no `lib` folder. I can build it locally for testing but I think something has gone wrong when the package was published. In fact, there is now `src` folder either.

**Comment by Nopzen** [comment]
Hmm this is pretty funny its been reported for `v1.x.x` aswell #134, but user claims it was a error on he's side.

**Comment by aklkv** [comment]
@Nopzen I can't think of anything that go wrong on my end.
![2017-05-03 05 42 58](https://cloud.githubusercontent.com/assets/312210/25661023/ab207664-2fc3-11e7-988c-b18bb2789bf0.gif)

**Comment by Nopzen** [comment]
Hi @aklkv 

Sorry the delayed answer here, let me try to look into this in the weekend, i think i have some time to do it there, in the mean time, if you still and to use this, you should be able to go to the director and run: `$ npm install && npm run build` this should create the lib i will have a small look today what i could have done wrong while publishing it.

@egeriis Could you have any idea what could have gone wrong here, sadly im not at the machine i published from right now, but if there is anything i could look for when i get to my other laptop i would love to hear ideas.

**Comment by egeriis** [comment]
It's probably a faulty publish. It's a pitty that it's not possible to check what has been published to NPM on their project page.

**Comment by Nopzen** [comment]
Hi @aklkv 

I can see @egeriis re-published the package under v2.0.0-beta.2 with a merge request of yours #137 could you see if this fixes your issue, so we could close down this?

**Comment by aklkv** [comment]
@Nopzen 👍 thank you! works great now
