### ISSUE TITLE
State not updateding and getting Response object with body ReadableByteStream

### ISSUE THREAD

**Issue by chrisjowen** [dixieio/redux-json-api#14]
Hey,

Firstly this is a nice project, Im new to react/redux and also the jsonapi spec so Im sort of fumbling my way through. That said I have an issue that I will fully accept could be on the part of my lack of understanding but here goes.

When I setup the api host/path and dispatch an action to read an entity I did expect that the state would be updated. However what I am seeing is that the state remains unaltered. I also hooked into you onsuccess callback but instead of the serialized json body I have a Response object. Here are the steps:
```
store.dispatch(setEndpointHost("http://localhost:4000"));
store.dispatch(setEndpointPath("/api"));
store.dispatch(readEndpoint("venue", {
        onSuccess: (result) => console.log(result),
        onError: (result) => console.error(result)
    }));
```
Resulting in:
```
Response {type: "basic", url: "http://localhost:4000/api/venue", status: 200, ok: true, statusText: "OK", body: ReadableByteStream...}
```

When I look at your code: https://github.com/dixieio/redux-json-api/blob/master/src/jsonapi.js#L243 I see that you expect the payload dispatched to have a data property which I haven't got. Is there some middleware magic at work here to convert this to what you need, and if so why do I still not see the state changing?

Cheer, Chris

**Comment by chrisjowen** [comment]
Actually, to further add to this I also get an error from API_READ_FAILED:

```Cannot read property 'payload' of undefined```

Though if I look at the network debugger in chrome I can see that the response was successful and looks like:

```
{"jsonapi":{"version":"1.0"},"included":[{"type":"user","id":"1","attributes":{"name":"Chris Owen","email":"chris.j.owen@hotmail.co.uk"}}],"data":[{"type":"venue","relationships":{"user":{"data":{"type":"user","id":"1"}}},"id":"1","attributes":{"website":"some content","postcode":"some content","phone":"some content","name":"some content","id":1,"city":"some content","address2":"some content","address1":"some content"}}]}
```

**Comment by egeriis** [comment]
Hi Chris,

Thank you for your questions.

`payload` is a property produced by the action creator: https://github.com/dixieio/redux-json-api/blob/master/src/jsonapi.js#L29

Look into `redux-actions` for more on how `createAction` works :)

What is the response body from your API? Are you sure it's JSON API compliant?

It is expected for the whole Response object to be passed to the `onSuccess` callback, as you might want to read header as well as response body.

The response body that you posted seems fine. I'm suspecting that the error occurs, trying to parse the body as JSON though. Could it be due to a missing `Content-Type: application/vnd.api+json` header in your response?

**Comment by chrisjowen** [comment]
Hey,

Thanks for the quick reply, I understand the payload is been created from the action coming from the api creator from createAction. I am unable to check right now the headers that I am returning are correct. I am using https://github.com/AgilionApps/ja_serializer which I believe does add the correct  application/vnd.api+json headers but I will check tonight. 

I think I recall looking at https://github.com/dixieio/redux-json-api/blob/master/src/utils.js#L20 and seeing that the correct call to ```res.json()``` was made, but as I said I cant be sure. Ill check tonight, and thanks again for the help.

**Comment by egeriis** [comment]
Did you have a look at #13? Another user had an issue, due to our library not properly parsing the `Content-Type` header, when a charset was passed along.

**Comment by egeriis** [comment]
We've pushed an update (v1.3.5) which should fix this issue. Can you confirm?

**Comment by chrisjowen** [comment]
@egeriis perfect, works like a char,

**Comment by egeriis** [comment]
Good to hear @chrisjowen
