### ISSUE TITLE
Update and improve README

### ISSUE THREAD

**Issue by justaskz** [dixieio/redux-json-api#22]
I am trying to use your library, but it is very hard. It seems that README is outdated. Could you please update it and also add atleast one full example, where you get data from server in your state? It would be very helpful!

**Comment by justaskz** [comment]
I managed to reach the point where my code makes a request to the endpoint and prints response

```
import { createAction } from 'redux-actions';
import { reducer, setEndpointHost, setEndpointPath, readEndpoint } from 'redux-json-api';

var _reducer = combineReducers({'api' : reducer})
const store = createStore(_reducer)

store.dispatch(setEndpointHost('http://localhost:3000'))
store.dispatch(setEndpointPath('/api/v1'))

readEndpoint('users')(store.dispatch, store.getState).then(function(res) {
  console.log(res);
})
```

**Comment by Nopzen** [comment]
Hi @justaskz 
Have you seen the issue's with header content-type #16 ?

Can you send me Content-Type in your response headers, just to check that aint whats messing you up? 

Thanks.

**Comment by egeriis** [comment]
@justaskz What is the issue you're experiencing? The four steps to get started is up to date. We acknowledge that it would be appropriate with a full example, but haven't been able to prioritize this yet. PRs are very welcome!

**Comment by justaskz** [comment]
@egeriis The problem is that `readEndpoint('users')` returns another function which expects `dispatch` and `getState` functions. And only after that I get a promise (this is the last call in my code snippet). 

So I made a conclusion, that either I missing something or README is out of date :D

**Comment by justaskz** [comment]
@Nopzen I dont have problems with with JSON parsing, I am struggling to understand how to use this library :)

**Comment by egeriis** [comment]
Yes, they are action creators, so you need to dispatch their return value, i.e. `dispatch(readEndpoint( ... ))`

**Comment by justaskz** [comment]
The problem was that I didnt know that it requires thunk. Now it works fine. I think we can close this issue, because there is a PR https://github.com/dixieio/redux-json-api/pull/25

**Comment by egeriis** [comment]
That's a good point @justaskz. We'll review that PR :) Thank you for your contributions.
