### ISSUE TITLE
Module not found: Error

### ISSUE THREAD

**Issue by Realtin** [dixieio/redux-json-api#27]
Hey,

while trying to get started with redux-json-api me and my coworker run into that error, while trying to start our application.

```
ERROR in ./~/redux-json-api/lib/jsonapi.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/defineProperty' in /Users/juliakruger/Repos/backoffice-react/node_modules/redux-json-api/lib
 @ ./~/redux-json-api/lib/jsonapi.js 3:23-70

ERROR in ./~/redux-json-api/lib/jsonapi.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in /Users/juliakruger/Repos/backoffice-react/node_modules/redux-json-api/lib
 @ ./~/redux-json-api/lib/jsonapi.js 7:16-56

ERROR in ./~/redux-json-api/lib/jsonapi.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/json/stringify' in /Users/juliakruger/Repos/backoffice-react/node_modules/redux-json-api/lib
 @ ./~/redux-json-api/lib/jsonapi.js 11:17-64

ERROR in ./~/redux-json-api/lib/jsonapi.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/promise' in /Users/juliakruger/Repos/backoffice-react/node_modules/redux-json-api/lib
 @ ./~/redux-json-api/lib/jsonapi.js 15:15-55

ERROR in ./~/redux-json-api/lib/utils.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in /Users/juliakruger/Repos/backoffice-react/node_modules/redux-json-api/lib
 @ ./~/redux-json-api/lib/utils.js 3:16-56
webpack: bundle is now VALID.
```

I tried to remove my node_modules, run `npm cache clean`and `npm install` but the errors was still there.
we could reslove this however, by adding your dependecies to our own:

```
npm install --save-dev babel-preset-stage-0 babel-plugin-transform-runtime babel-plugin-add-module-exports
npm install --save babel-runtime
```

do you know what is happening there?

**Comment by egeriis** [comment]
It's not an issue we've seen before. But you should probably try to investigate on that error, if it isn't something with your babel binary or something like that. 

We're not referencing any of the listed modules in this library, so it's probably a babel or webpack issue that occurs when transforming from ES6 to ES5.

**Comment by egeriis** [comment]
For the record, we're using babel 6.3 in our projects.

**Comment by makeitTim** [comment]
I also ran into this problem whiling setting up my project on another computer. This wasn't happening before on previous setups --- inferring something has changed with one of the packages involved. The fix @Realtin gave of manually installing the dependencies worked.

My Babel versions is: `"babel-core": "^6.7.6"`

**Comment by Realtin** [comment]
We are using `"babel-core": "^6.7.6"` as well!

**Comment by caalle** [comment]
I'm also running into the same issue, any updates on this?

**Comment by egeriis** [comment]
@caalle I think we're simply missing a dependency in package.json. We'll look into this asap.

**Comment by egeriis** [comment]
@caalle @makeitTim @Realtin Can any of you add some steps to reproduce?

**Comment by bhtabor** [comment]
I was getting a similar error on a fresh [create-react-app](https://github.com/facebookincubator/create-react-app) and importing redux-json-api. They happen to have a different version of babel-runtime and that could be the cause. `rm -rf node_modules && npm install` resolved the issue for me.
