### ISSUE TITLE
Uselessness of redux-json-api

### ISSUE THREAD

**Issue by asiniy** [dixieio/redux-json-api#36]
Please correct me if I'm wrong.

Let's say I have a simple structure, like `Post` & `Comment`. Read endpoint returning both tasks & comments which are belongs to tasks. So, I have a structure like:

``` javascript
state: {
  api: {
    posts: [array of posts with their ids],
    comments: [array of comments with their ids]
  }, ...
}
```
I want to get only one element to show it on the page. It requires a js method like [find](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/find) to find a particular post. But after it I need to find a comments for this post, which requires a lot of magic too. Is there any helpers methods or something like that to make structure working elegant?

**Comment by egeriis** [comment]
At the moment, we're sketching out possible solutions to this problem. It's not the current scope of the project, but an obvious addition. If you would like to participate, please consider use cases that you would like to have supported, then note them here 💜

**Comment by asiniy** [comment]
The best solution in my opinion - is to write custom function, like `findResource(id, state)`, which takes an id and return model and association. I can write PR if you want to

**Comment by asiniy** [comment]
I found that it's no problem to handle a lot of data collected by javascript `find()` method. You can do something like

``` javascript
mapStateToProps = (state, props) => {
  post = state.api.posts.data.find(function(el) { return el == props.params.id }) // props.params.id is react-router prop

  return { post: post }
}
```

there are no difficulties here... But. How can I fetch something if I have an search page and results depend on some queries I'm sending? I wouldn't implement filter according to params or something like that.

I presume best idea here - is to write action like `emptyAPI`. In this case user can empty his data before action when he needs all data to be used. WDYT?

**Comment by Nopzen** [comment]
@asiniy 

It is possible to extend our api localy to empty the api if that is needed. By simply just writing a emptyAPI(keyName) and then reduce the Redux store.

_Regarding a `emptyApi()`, it is flaged in another issue aswell, and one of the many small api's we want to integrate into the tool. #24 (also releated to a search feature)

**Comment by asiniy** [comment]
@Nopzen ok, will try to do that

**Comment by egeriis** [comment]
@asiniy Do you have anything to add? Otherwise we'll close the thread :)

**Comment by asiniy** [comment]
@egeriis I did that for you
