### ISSUE TITLE
Consider documenting return signature of readEndpoint

### ISSUE THREAD

**Issue by wiltzius** [dixieio/redux-json-api#38]
Hello,

I've started playing around with redux-json-api, migrating from a JSON API JS client my team wrote ourselves. So far it's wonderfully easy to use (well, after I read the docs in progress in #31 :) ), but I'm stuck on one common case that I don't see a natural pattern for. If you perform an endpoint read that returns multiple results (as in the case for e.g. a search query), state.api is populated with all of them correctly -- but how do you know which entries correspond to the API read you just issued, as opposed to another API read?

I think the way around this looks something like this (below is a simplified example):

- an additional reducer:
```javascript
const queryStore = (state={}, action) => {
  if(action.type == 'API_READ') {
    return Object.assign({}, state, {[action.payload.endpoint]: action.payload.data.map(el => el.id)});
  }
  else {
    return state;
  }
};
```
- an action dispatch that looks like this:
```javascript
this.props.dispatch(readEndpoint('/api/path?search=' + state.foo));
```
- and a mapStateToProps that looks like this:
```javascript
function mapStateToProps(state) {
  return {
    search_results: (state.queryStore['/api/MyObject?search=' + state.foo]).map(id => {
      return _.find(state.api.MyObject.data, {id: id});
    });
}
```

... but the additional reducer and the additional queryStore state entry to keep track of outstanding queries makes it seem like I'm doing something wrong, since that's all stuff I would assume the library would track. This is also a very naive implementation, so e.g. you need to manually remove entries from state.queryStore if you want to re-issue the find.

Am I missing something, or is this how the library is meant to be used?

**Comment by wiltzius** [comment]
Also, I read through the discussion in issue 24, which gets at some of the difficulty I mentioned of clearing the results if you want to issue multiple queries to the same path/params. But that discussion seems to suppose there's already a way to handle search results (ignoring the clearing issue), making me wonder if I'm just missing something. So, this might be a more of a documentation request than a missing feature :)

**Comment by egeriis** [comment]
For the cases where it is necessary to do something as implementation specific, you can use the promise that is returned when a `readEndpoint` action is dispatched. This promise will get the response as it's lone argument. Using this response to read the returned ID's or something similar, would be my recommendation on how to make this work, if the search results may get mixed in between other resource objects.

This is an example of how I conceptually image that this could work. 

```js
dispatch(readEndpoint('search?name=foo')).then(response => {
  response.json().then(
    r => this.setResultIds(r.data.map(entity => entity.id))
  );
});
```

Where `setResultIds` would be responsible to registering the result entity IDs in some other state.

Does that makes sense for your use case?

**Comment by wiltzius** [comment]
Ah, I did not realize that the dispatch returned a promise with the response contents! That greatly simplifies things, and was the piece I was missing. So then this is just a documentation request. I don't think the new documentation in #31 mentions the promise at all, I guess this is meant to be implied by the use of redux-thunk but I think all that does is allow an action creator to return a promise... the fact that the readEndpoint action creator does, and what the promise contents are, should maybe be documented.

I've updated the title to be about the documentation rather than my original question, but feel free to close the issue if it isn't useful to you. I appreciate the help, thank you!

**Comment by egeriis** [comment]
It's a good point that it's lacking from the documentation, we'll make sure to add it. 

I don't think that the use of _redux-thunk_ is enough of a hint to imply that the actions may return a Promise. Considering that the return value can be any value :)

**Comment by egeriis** [comment]
I'm adding a note to #31 that we need to mention promises, so I'll close this issue :)
