### ISSUE TITLE
Can I set cookie in header, how?

### ISSUE THREAD

**Issue by JaylonQi** [dixieio/redux-json-api#45]

**Comment by Nopzen** [comment]
Hi @JaylonQi 
 - Im not sure are you asking if you can set a header based of a cookie 
 - Or if you can set a cookie in the header?

Would like to know a bit more of the use case here?

**Comment by egeriis** [comment]
We currently use `fetch` to make the async API calls. By default it doesn't send cookies to the server; https://github.com/github/fetch#sending-cookies

**Comment by asiniy** [comment]
@JaylonQi there are two ways to implement it:

1. Change `fetch` configs directly into `node_modules` dir;
2. Use this PR branch: https://github.com/dixieio/redux-json-api/pull/41 feel free to set up cookie as you want

**Comment by JaylonQi** [comment]
Oh yeah, thank you all guys.
I have change fetch options in the redux-json-api to make the fetch take the cookie to the back.

**Comment by gazpachu** [comment]
@JaylonQi do you mind posting the change you did to make it work? Thanks!
