### ISSUE TITLE
Link to JSONAPI in the readme is wrong

### ISSUE THREAD

**Issue by Dinoshauer** [dixieio/redux-json-api#52]
Hey peeps,

`www.jsonapi.org` doesn't resolve but `jsonapi.org` does :)

Just a heads up!

**Comment by Nopzen** [comment]
Thanks @Dinoshauer  ill fix it now :p

**Comment by Nopzen** [comment]
Fixed in https://github.com/dixieio/redux-json-api/commit/10788593036c4884d53f07678fc951af4994865b
