### ISSUE TITLE
Pass custom options to fetch

### ISSUE THREAD

**Issue by jbadger** [dixieio/redux-json-api#53]
There is currently no way (that I can see) to pass custom options to the fetch function in utils.js.  I need to be able to pass `credentials: 'include'` in the options hash for basic auth to work.

It'd be nice to set this as a global config option like host and path.

**Comment by jbadger** [comment]
Part two to making basic auth work is in https://github.com/dixieio/redux-json-api/issues/54

**Comment by egeriis** [comment]
This will be included in v2.0 which includes a change from fetch to Axios #41

**Comment by evolve2k** [comment]
@jbadger this credentials issues has just been fixed and is live now in newly released v1.5.4

**Comment by license2e** [comment]
@egeriis Any chance `credentials: 'include'` can be an optional setting instead of adding it by default?
