### ISSUE TITLE
Error on deleteEntity

### ISSUE THREAD

**Issue by DanBradbury** [dixieio/redux-json-api#60]
I'm getting a strange error when deleting a resource using `deleteEntity`.

```
Uncaught (in promise) TypeError: Cannot read property 'indexOf' of null(..)
            (anonymous function)	@	utils.js:32
            (anonymous function)	@	utils.js:31
```

from `utils.js`
```
    if (res.status >= 200 && res.status < 300) {
      if (jsonContentTypes.some(function (contentType) {
        return res.headers.get('Content-Type').indexOf(contentType) > -1; //breaks here
      })) {
        return res.json();
      }

      return res;
    }
```

The `DELETE` request is successful and the server responds with `204 No Content`

Since the server is correctly implementing the [jsonapi spec for delete](http://jsonapi.org/format/#crud-deleting) (using [`jsonapi-resources`](https://github.com/cerebris/jsonapi-resources)) I'd expect there to be no problem when the response is handled by `redux-json-api`

We were thinking this could have just been an issue with a missing `Content-Type` header but from the [HTTP/1.1 RFC](https://tools.ietf.org/search/rfc2616#section-7.2.1) we see that `Content-Type` isn't even mandatory when content is available.
> Any HTTP/1.1 message containing an entity-body SHOULD include a Content-Type header field defining the media type of that body

From reading up on `jsonapi-resources` they made a [conscious decision](https://github.com/cerebris/jsonapi-resources/pull/69) to not include `Content-Type` on `204 No Content` which makes sense to me (no content is coming back in the response so why provide a `Content-Type` for something that doesn't exist)

Is this something that should be fixed on the server side? Or would it make more sense to adjust the above code to handle the `res.status === 204` case?

**Comment by Realtin** [comment]
I have the same issue.

**Comment by egeriis** [comment]
That's interesting. I never noted that the spec notes: 
> Any requests that _contain content_ 

That's definitely an oversight. 

I reckon a quick fix would be a check on status code, as you suggest. The correct solution would probably be to check if there is any data in the response body, but I am not even sure that JSON API allows GET, PATCH and POST response body to be empty.

Are you up for making a PR @DanBradbury?

**Comment by Petesta** [comment]
:simple_smile:

**Comment by DanBradbury** [comment]
When updating relationships w/ `PATCH` [it may return](http://jsonapi.org/format/#crud-updating) a 204
> If an update is successful and the server doesn’t update any attributes besides those provided, the server MUST return either a 200 OK status code and response document (as described above) or a 204 No Content status code with no response document.

The same is true for [creating resources](http://jsonapi.org/format/#crud-creating) (`POST`); must return either `201` or `204` on success

I wasn't aware of any 204s until this morning and can submit a PR to take a look at the status code. I'm under the impression that whenever we have a `204` status the body should be empty (not sure if there is a case where you'd want to return any other code with an empty body)

**Comment by egeriis** [comment]
> not sure if there is a case where you'd return any other status code with an empty body

No, I think you're right. At least that would fall out of scope, as the API doesn't follow the spec then.

**Comment by DanBradbury** [comment]
I went ahead and took a stab at taking care of this. Please review PR #61

**Comment by zweck** [comment]
I'm having this same issue, our JSON-API serializer (https://github.com/fortunejs/fortune-json-api) seems to return `204` for updates by default which is also throwing:

```
Uncaught (in promise) TypeError: Cannot read property 'indexOf' of null(..)
            (anonymous function)    @   utils.js:32
            (anonymous function)    @   utils.js:31
```

**Comment by evolve2k** [comment]
Pull request #61 which resolves this issue has been merged in the last day or so.

@egeriis This issue can now be closed 🚪

**Comment by egeriis** [comment]
I forgot to close the issue 🙂 Expected it to be closed automatically.
