### ISSUE TITLE
Duplicated entries

### ISSUE THREAD

**Issue by gazpachu** [dixieio/redux-json-api#64]
I'm not sure the root > topics entries in the redux store are duplicated. In the JSON file there are only 5 but in the redux store appear 10. Any idea of what could be wrong?

JSON file: http://vf-snowden-staging.herokuapp.com/topics/root

<img width="212" alt="screen shot 2016-09-23 at 16 04 15" src="https://cloud.githubusercontent.com/assets/1721288/18790969/d37e0c08-81a8-11e6-9d52-dd34d83f1643.png">

**Comment by egeriis** [comment]
@gazpachu That's interesting. This shouldn't be possible, but we have never used string IDs ourselves. If you can create a PR, we'd be happy to resolve this asap. Remember to include broken test before implementing a fix :)

**Comment by gazpachu** [comment]
@egeriis thanks. I think there was a problem with the JSON. I cannot replicate the issue anymore.

**Comment by egeriis** [comment]
@gazpachu Happy to hear that you found a resolution. Let us know if problem re-appers.
