### ISSUE TITLE
Cookie based session credential authentication is not currently supported

### ISSUE THREAD

**Issue by evolve2k** [dixieio/redux-json-api#65]
I have a redux app that is connected with a Rails backend using the '[react_on_rails](https://github.com/shakacode/react_on_rails)' ruby gem.

My redux app was correctly authenticating updates to my backend until I shifted across to redux-json-api. After a lot of hunting around we found that I was doing the call previously with the jquery ajax command and redux-json-api relies upon the newer fetch approach which we found out no longer sends cookies by default and hence the rails backend was not getting sent the session authentication cookie it was expecting.

This turns out to have a quick fix. 

**Calls to fetch just need to have credentials: 'include', added to them to once again pass credential information across.**

Reference: https://developers.google.com/web/updates/2015/03/introduction-to-fetch#sending-credentials-with-a-fetch-request

> ### Sending Credentials with a Fetch Request
> Should you want to make a fetch request with credentials such as cookies, you should set the credentials of the request to “include”.
> 
> ```
> fetch(url, {  
>   credentials: 'include'  
> })
> ```

I've created a branch that include the changes mentioned and I've got it working with my local app, but my JS skills are limited and so I don't currently have any test coverage.

Here's the change:
https://github.com/evolve2k/redux-json-api/commit/b384db6cfbe4c0e3d71f7e83a3e5f9dd0e8ab488

I'm hoping a more experienced dev could possibly help get this polished up into an acceptable pull request unless you think it's simple enough as it is.

**Comment by egeriis** [comment]
We are currently working on updating the library to use [Axios](https://github.com/mzabriskie/axios) instead. This would make it far easier for you to tailor the requests our library makes for your implementation purpose. 

Hopefully we can get this closed within a few weeks. Is this functionality urgent for you, or are you relying on your fork to have your application working currently?

**Comment by jbadger** [comment]
I'm relying on a fork for this same issue:  https://github.com/dixieio/redux-json-api/issues/53

And related issue: https://github.com/dixieio/redux-json-api/issues/54

**Comment by evolve2k** [comment]
I am needing this and it will affect anyone using redux-json-api with a Rails backend AFAIK.
It was a real sticking point that it wasn't there, as I mentioned I spent ages debugging to discover this was the issue.

Would hugely appreciate if it could possibly be included as it's really a requirement to be able to use this library at the moment,  happy to have it deprecated at a later date when version 2 or such finally comes around.

Thanks!

**Comment by egeriis** [comment]
Really depends on your auth strategy. I would be surprised if there are no other auth strategy than cookie based in Rails :) Especially considering that cookies are not best practice.

**Comment by evolve2k** [comment]
I am using a different auth strategy that properly authenticates the user. As added security in rails a session cookie is also created and is expected to be returned by forms submitting to rails, this cookie also lets me know the current_user object which simplifies things greatly on my end.

This will very much help me deploy without issue and without having to migrate to v2.0 before getting some results. I would again request would it be possible to just include 'credentials: include' into version 1 and this would make such a difference for me just getting this app shipped.

Thanks

**Comment by egeriis** [comment]
Ah, it's a CSFR check?

@jbadger Which fork are you relying on? I reckon we haven't received a PR for this.

**Comment by evolve2k** [comment]
Yep for CSRF.

**Comment by evolve2k** [comment]
@egeriis I've just added a pull request for this. As I've mentioned my JS skills are limited so if you're willing to enhance this yourself if you see any issues with it, that'd be greatly appreciated.
