### ISSUE TITLE
Etags

### ISSUE THREAD

**Issue by cfey** [dixieio/redux-json-api#67]
Hi guys,
first of all thanks for the awesome work!

I'm quite new to React - Redux and your awesome library

I have a question regarding ETags.
Does your library support ETags? and if, how?

Conventionally I tried to pass a 2nd argument into `readEndpoint` like
 `readEndpoint(route, {'If-None-Match': '123'})`

But apparently that doesn't work. :/

Cheers

**Comment by egeriis** [comment]
Hi @cfey,

Thank you for your question and interest in our library.

Etags are not supposed to be implemented in clients, they are implemented by the browsers. If your API responds with the correct headers, you should be good to go. 

—R

**Comment by cfey** [comment]
AFAIK that's true for files (images, etc.) but apparently doesn't work for json responses
for example:
If I request an item from my API, I get an ETag in the header. When I request the same item again with the request header "If-None-Match" set to the given Etag, the response is a 304
Without the "If-None-Match" header I get a 200.

Maybe I'm wrong, but what I read so far comes down to, that I have to store the ETag and send it with the request as "If-None-Match" header

**Comment by egeriis** [comment]
As far as I can see, etags are not supported by fetch, which we rely on for the requests. However in v2.0 we will shift to Axios, which uses AJAX requests by default. Thus you will probably have to wait for this or see if you can implement this lib: https://github.com/export-mike/f-etag
