### ISSUE TITLE
Map the 'included' section from the JSON as a prop

### ISSUE THREAD

**Issue by gazpachu** [dixieio/redux-json-api#69]
In the docs, it shows how to map 'data' as a prop, but what about 'included'?

I've tried like this, but it doesn't show up:

`const mapStateToProps = ({ api: { topics = { data: [], included: [] } } }) => ({ topics });`

**Comment by Nopzen** [comment]
Hi @gazpachu 

When a Request is resolved, the included data will be merged with data, and then reduced on to your API key, in this case `topics`

We dont expose the include, since `redux-json-api`merges them internally.

Hope this helps?

**Comment by gazpachu** [comment]
Hmm, I don't see it inside topics. Maybe I'm missing something.

**Comment by Nopzen** [comment]
Can you show me your `readEndpoint` dispatch, and the response from the server ?

**Comment by gazpachu** [comment]
Original JSON from the server:

```
{
  "data": [
    {
      "type": "topics",
      "id": "total-contract-value",
      "attributes": {
        "name": "Total Contract Value",
        "level": 0
      },
      "links": {
        "self": "/topics/total-contract-value"
      },
      "relationships": {
        "parent": {
          "data": null
        },
        "question": {
          "data": null
        },
        "topics": {
          "data": [
            {
              "type": "topics",
              "id": "sales-performance"
            }
          ]
        }
      }
    },
    {
      "type": "topics",
      "id": "effort",
      "attributes": {
        "name": "Effort",
        "level": 0
      },
      "links": {
        "self": "/topics/effort"
      },
      "relationships": {
        "parent": {
          "data": null
        },
        "question": {
          "data": null
        },
        "topics": {
          "data": []
        }
      }
    },
    {
      "type": "topics",
      "id": "money",
      "attributes": {
        "name": "Money",
        "level": 0
      },
      "links": {
        "self": "/topics/money"
      },
      "relationships": {
        "parent": {
          "data": null
        },
        "question": {
          "data": null
        },
        "topics": {
          "data": []
        }
      }
    },
    {
      "type": "topics",
      "id": "budget",
      "attributes": {
        "name": "Budget",
        "level": 0
      },
      "links": {
        "self": "/topics/budget"
      },
      "relationships": {
        "parent": {
          "data": null
        },
        "question": {
          "data": null
        },
        "topics": {
          "data": []
        }
      }
    },
    {
      "type": "topics",
      "id": "leaderboard",
      "attributes": {
        "name": "Leaderboard",
        "level": 0
      },
      "links": {
        "self": "/topics/leaderboard"
      },
      "relationships": {
        "parent": {
          "data": null
        },
        "question": {
          "data": null
        },
        "topics": {
          "data": []
        }
      }
    },
    {
      "type": "topics",
      "id": "sales-performance",
      "attributes": {
        "name": "Sales performance",
        "level": 1
      },
      "links": {
        "self": "/topics/sales-performance"
      },
      "relationships": {
        "parent": {
          "data": {
            "type": "topics",
            "id": "total-contract-value"
          }
        },
        "question": {
          "data": null
        },
        "topics": {
          "data": [
            {
              "type": "topics",
              "id": "by-employee"
            }
          ]
        }
      }
    },
    {
      "type": "topics",
      "id": "by-employee",
      "attributes": {
        "name": "By employee",
        "level": 2
      },
      "links": {
        "self": "/topics/by-employee"
      },
      "relationships": {
        "parent": {
          "data": {
            "type": "topics",
            "id": "sales-performance"
          }
        },
        "question": {
          "data": {
            "type": "questions",
            "id": "1"
          }
        },
        "topics": {
          "data": []
        }
      }
    }
  ],
  "included": [
    {
      "type": "questions",
      "id": "1",
      "attributes": {
        "title": "How are my employees performing?",
        "clarification": "Rejected opportunities are excluded from the achievement figures. Includes historic changes of allocations and hierarchy",
        "methodology": "BLA BLA BLA"
      },
      "links": {
        "self": "/questions/1"
      },
      "relationships": {
        "filters": {
          "data": []
        },
        "charts": {
          "data": []
        },
        "tables": {
          "data": []
        }
      }
    }
  ]
}
```

Console.log of the readEndPoint:

![screen shot 2016-09-30 at 14 12 35](https://cloud.githubusercontent.com/assets/1721288/18992774/068ad7ba-8718-11e6-85d5-702ceb16f651.png)

Data in the redux store using React Dev Tools:

![screen shot 2016-09-30 at 14 14 09](https://cloud.githubusercontent.com/assets/1721288/18992792/250c485e-8718-11e6-9ab4-494c48f1f074.png)

**Comment by Nopzen** [comment]
@gazpachu - Your included data should be under apikey `questions` - becuase the type of the data is `questions` :)

**Comment by gazpachu** [comment]
@Nopzen do you mean like this?

```
{
    "data": [],
    "questions": [
        "included": [
    {
      "type": "questions",
      "id": "1",
      "attributes": {
        "title": "How are my employees performing?",
        "clarification": "Rejected opportunities are excluded from the achievement figures. Includes historic changes of allocations and hierarchy",
        "methodology": "BLA BLA BLA"
      },
      "links": {
        "self": "/questions/1"
      },
      "relationships": {
        "filters": {
          "data": []
        },
        "charts": {
          "data": []
        },
        "tables": {
          "data": []
        }
      }
    }
  ]
    ]
```

**Comment by Nopzen** [comment]
No, What i mean is on the API key on your redux state [explained here](https://github.com/dixieio/redux-json-api/blob/master/docs/set-up-configure.md) - the section called: _Add reducer to api namespace_ 

There should now be a key called `questions` after the include call have been successful resolved.

**Comment by gazpachu** [comment]
I'm not sure I understand what you mean. Like this?

```
import { combineReducers } from 'redux';
import { reducer as api } from 'redux-json-api';

export default combineReducers({
  api,
  questions
});
```

**Comment by Nopzen** [comment]
@gazpachu  Show me the Redux state after the request is successful, Becuase it should be there.

You should not handle the storing of included data your self that is what the tool should do, the console log you ref. to is correct it shows the data as it should be. 

The screenshot where you show `topics` is also correct, it should not be stored under topics. it should be stored under key `questions`

So look for this

`store.apiKey.questions` - replace `apiKey` with what ever you have set up the reducer with.  It will be there.

See this example:

First im fetching some posts by just calling my posts endpoint:
![skaermbillede 2016-10-03 kl 12 59 36](https://cloud.githubusercontent.com/assets/2326591/19035370/6bd46c28-8969-11e6-9016-e2c616b62960.png)

This stores my data on my `store.api.posts` (3 posts in this case)

Secondly i fetch my posts again, and then i __include__ `post.createe` in this case a createe is a type of `users` that will then store all the includes users under `store.api.users`

![skaermbillede 2016-10-03 kl 13 00 11](https://cloud.githubusercontent.com/assets/2326591/19035409/ad0af0d6-8969-11e6-9767-2f1a88746401.png)

This is excatly what should happen for your includes aswell, and the it seems from the provides snipets that is what happens. If it doesn't happen you might have a setup issue.

**Comment by gazpachu** [comment]
In the Redux dev tools it shows up correctly! O_O

![screen shot 2016-10-03 at 12 43 34](https://cloud.githubusercontent.com/assets/1721288/19036318/07ec0204-8967-11e6-983f-3efd37f32818.png)

**Comment by Nopzen** [comment]
Check the state then,  it should be there under the `state.apikey.questions` from there you are able to access it.

**Comment by Nopzen** [comment]
The INCLUDED data will be stored under the INCLUDED entiy types, __NOT__ under `topics`

Try this for you're mapStateToProps.
`const mapStateToProps = ({ api: { topics, questions }) => ({ topics, questions });`

**Comment by gazpachu** [comment]
`const mapStateToProps = ({ api: { topics = { data: [] }, questions = { data: [] } } }) => ({ topics, questions });`

That returns this error: useQueries.js?335c:115Uncaught (in promise) TypeError: Cannot read property 'query' of undefined(…)

`const mapStateToProps = ({ api: { topics, questions }}) => ({ topics, questions });`

That returns this error: Uncaught TypeError: Cannot read property 'data' of undefined

**Comment by Nopzen** [comment]
Ahh yeah i forgot to unpack data, and/or set a default data empty array my bad, for you in my example witch will result in the latter error.

How every the first error seems like we are on to somthing right here, but that is nothing i can help you with, since it looks like your are trying to read key `query` from some object im not aware of, set a break point in your `useQueries.js` and figure whats going on there.

But take a look in the redux dev tools under the `state` key after the `API_READ` and you should be able to see questions.

**Comment by gazpachu** [comment]
You are right. With the first line of code it works! even if it throws the error about the query. I don't know what's that all about

**Comment by Nopzen** [comment]
No problem happy to help.
