### ISSUE TITLE
How to use my own fork of this repo on github

### ISSUE THREAD

**Issue by evolve2k** [dixieio/redux-json-api#70]
Hey I've forked the repo and been playing around with my own changes but I keep needing to manually copy the changes into the node_modules directory of my project and Im also having random dependancy issues depending on what Im trying to do.

I've asked generically on SO, and googled a lot but it seems it's an it depends type answer.

I figured you folks are regularly working on this code and have your own private branches you're possibly developing.

What do I need to do to the project so that I can use my own fork, it seems I need to compile it so that dependancies are included and ensure that's available on the github repo from my understanding.

(Specifically right now Im monkey patching the code to test my issue of what if I forced the url to include a caterpillar/dasherized version of the entity.type in the path, as per this issue (https://github.com/dixieio/redux-json-api/issues/62) but Im also wanting to test my own code changes with this repo generally).

Just to clarify I know how to refer to my own repo from package.json like so,
`"redux-json-api": "https://github.com/evolve2k/redux-json-api.git#dasherized",`
but Im needing to know how to prepare the repo so it just works when referred to as above.

Thx

**Comment by Nopzen** [comment]
Hi @evolve2k 

The way that we are doing this our selfs is we are using the `$ npm link` feature, what this does it it creates a symlink too the npm package, then we do changes in the package run the `$ npm build` and then refresh our browser. and it should work

### How to set up the link
1. Go to your local fork, in the root (where package.json is located), and write `$ npm link`
 - It should spit domething like this back `/Users/larsfalcon/.nvm/versions/node/v4.0.0/lib/node_modules/redux-json-api -> /Users/larsfalcon/Documents/lkrieger/git/redux-json-api`
2. Go to your frontend repo and write `$npm link redux-json-api`
 - It should respond like this `/Users/larsfalcon/Documents/dixie/dez/node_modules/redux-json-api -> /Users/larsfalcon/.nvm/versions/node/v4.0.0/lib/node_modules/redux-json-api -> /Users/larsfalcon/Documents/lkrieger/git/redux-json-api`

This have now set up a symbolic link to your local fork, you can now edit the `redux-json-api` localy and run the build command.

Beaware there can be a few issues with depenencies. If you are running webpack. But they should be easy to resolve.

Another solution could be just set your own fork as the package in NPM and directly download it from your own hosted version on git hub.

I hope this helps you.

**Comment by evolve2k** [comment]
Thankyou! 

I've given this a go, but am getting this warning.
Locally I ran:

`$> npm run build`

Then on booting my app, I'm getting:
```
10:51:37 client.1 | WARNING in ./~/redux-json-api/lib/jsonapi.js
10:51:37 client.1 | Critical dependencies:
10:51:37 client.1 | 1:480-487 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
10:51:37 client.1 |  @ ./~/redux-json-api/lib/jsonapi.js 1:480-487
```

**Comment by Nopzen** [comment]
HI @evolve2k 

I just did a small reading on this, that this is just a guideline to dont do this in "production" you application should still work, we have never seen this our self, it looks like a setting in your webpack setting that it will show these errors, altho im not sure.

If the application running as intended or does this block your application ?

**Comment by evolve2k** [comment]
Yeah it's blocking the app from running.

**Comment by Nopzen** [comment]
Okay, Uhm right now i cant tell why due to i've never experiences this error, but lets do a bit of research on this, we have only experiences that it would have a hard time on the linter & missing dependencies.

**Comment by Nopzen** [comment]
@evolve2k 
I think this thread is what you want to look at: https://github.com/webpack/webpack/issues/1617 ? Maybe you could find some assistance here.

**Comment by Nopzen** [comment]
@evolve2k as a last resort you could try is to replace in your `package.json` our package with your own fork _(github url)_, it should work aswell, if this `npm link` is causing more issues than good, it is notorious for being a bit wired with webpack, its not the first time i've seen funky errors with it.

**Comment by evolve2k** [comment]
I had limited luck getting this going, but it's not something Im needing urgently for now. So will close this issue to get it off the plate. I can always reopen at a later date if I come back to wanting to do this.

Thanks for your help and suggestions.

**Comment by egeriis** [comment]
@evolve2k I'm not sure we can do much to mitigate this? Your app build script is correctly suggesting that the source file is pre-built.

Not sure about your set-up, but maybe you could just reference the file which is not build?
