### ISSUE TITLE
Consider setup of a gitter to help move some of the tricker project issues along with more direct communication?

### ISSUE THREAD

**Issue by evolve2k** [dixieio/redux-json-api#77]
Would you peeps consider setting up a gitter for the project or are you ever anywhere on IRC this might be easier to resolve over IRC chat, I've made good progress doing so on the other side of the equation chatting on the jsonapi-resouces ruby gem using their gitter.

http://gitter.im/cerebris/jsonapi-resources

Just putting it out there as I've definitley found it slower going with a day by day back and forth on issues that would be better resolved on both sides with more direct communication.

**Comment by evolve2k** [comment]
I'm guessing this is too much for you folks at this stage. Just an idea. 
Closing issue.

**Comment by egeriis** [comment]
We don't have that much manpower behind this project currently. But if it would create a community around the project, I think it's a great idea. If that wouldn't happen, I guess we would create false expectations with regards to response time or availability.

Your thoughts?
