### ISSUE TITLE
Mix api reducer with another custom reducer

### ISSUE THREAD

**Issue by gazpachu** [dixieio/redux-json-api#78]
Hi,

So far I had no issues with mapping to props the types received from my API reducer, but now I find myself in the need of combining the map to props from the API and from another reducer `mainReducer` I'm using in the app.

How can I combine the two reducers when mapping to props? This is how I'm trying to do it:

```
const mapStateToProps = ({
	api: {
		questions = {
			data: []
		},
		filters = {
			data: []
		},
		tables = {
			data: []
		},
		columns = {
			data: []
		},
		answers = {
			data: []
		}
	},
	mainReducer: {
		currentFilters = {
			data: []
		}
	}
}) => ({ questions, filters, tables, columns, answers }, { currentFilters });

function mapDispatchToProps(dispatch) {
	return bindActionCreators({ setFilters: setFilters }, dispatch);
}

export default connect(mapStateToProps, mapDispatchToProps)(Report);
```

This approach is giving me an error that I wasn't getting when I only had the API stuff:

`Uncaught (in promise) TypeError: this.props.dispatch`

**Comment by egeriis** [comment]
Your `mapStateToProps` function has invalid syntax, as the following is not a valid return statement.

```js
({ questions, filters, tables, columns, answers }, { currentFilters })
```

**Comment by gazpachu** [comment]
Hi @egeriis, could you please let me know how to do it? It can be also useful for documentation purposes (i.e. how to combine API and custom reducers). Many thanks!

**Comment by egeriis** [comment]
I reckon this should work:

```js
({ questions, filters, tables, columns, answers, currentFilters })
```

**Comment by gazpachu** [comment]
Hmm, that doesn't seem to work:

```Uncaught TypeError: this.props.dispatch is not a function```

I think because the custom reducer stuff doesn't implement the dispatch function?

**Comment by gazpachu** [comment]
Fixed it! No need to use bindActionCreators anymore:

```const mapDispatchToProps = {
	setLoading,
	setOpened,
	changeViewport,
	readEndpoint,
	setEndpointHost,
	setEndpointPath,
	setAccessToken
};```

**Comment by egeriis** [comment]
I am not sure. It's definitely not something in our lib :)
