### ISSUE TITLE
readEndpoint in a container with mapDispatchToProps

### ISSUE THREAD

**Issue by gazpachu** [dixieio/redux-json-api#79]
Hi,

I have a container, `app.jsx`, which already has `mapStateToProps` and `mapDispatchToProps` for a custom reducer I built called `mainReducer`. If I use the method explain in the docs to read an API endpoint, (`this.props.dispatch(readEndpoint(...))`), then I would get this error: `Uncaught TypeError: this.props.dispatch is not a function`. I guess because I'm using `mapDispatchToProps` for my custom reducer and that conflicts with the library.

The only way to make it work with `readEndpoint` was to add `readEndpoint, setEndpointHost, setEndpointPath, setAccessToken` to `mapDispatchToProps`, which changes the way I call these methods (I no longer use `.dispatch()`):

```
componentDidMount() {
		this.props.setEndpointHost(API_URL);
		this.props.setEndpointPath(API_PATH);
		this.props.readEndpoint('start');
	}
```

```
const mapStateToProps = ({ mainReducer: { isLoading, isOpened, isDesktop }, api: { start = { data: [] }, header = { data: [] } } }) => ({ isLoading, isOpened, isDesktop, start, header });

const mapDispatchToProps = {
	setLoading,
	setOpened,
	changeViewport,
	readEndpoint,
	setEndpointHost,
	setEndpointPath,
	setAccessToken
};

export default connect(mapStateToProps, mapDispatchToProps)(App);
```

So far, so good, the problem comes when in a child container `navigation.jsx`, I need to make another `readEndpoint`. In this case, because I passed down all the props from `app.jsx` to the children, then when I try to make the calls, I always get an infinite loop with the following errors:

`warning.js?0260:36 Warning: performUpdateIfNecessary: Unexpected batch number (current 1638, pending 1637)printWarning @ warning.js?0260:36warning @ warning.js?0260:60performUpdateIfNecessary @ ReactReconciler.js?6bfa:150runBatchedUpdates @ ReactUpdates.js?ce09:151perform @ Transaction.js?6dff:138perform @ Transaction.js?6dff:138perform @ ReactUpdates.js?ce09:90flushBatchedUpdates @ ReactUpdates.js?ce09:173closeAll @ Transaction.js?6dff:204perform @ Transaction.js?6dff:151batchedUpdates @ ReactDefaultBatchingStrategy.js?ef70:63enqueueUpdate @ ReactUpdates.js?ce09:201enqueueUpdate @ ReactUpdateQueue.js?fd2c:25enqueueSetState @ ReactUpdateQueue.js?fd2c:210ReactComponent.setState @ ReactComponent.js?702a:64handleChange @ connect.js?243b:301dispatch @ createStore.js?fe4c:186dispatch @ VM1325:1(anonymous function) @ index.js?f248:14dispatch @ applyMiddleware.js?ee15:45(anonymous function) @ jsonapi.js?64db:204
warning.js?0260:36 Warning: performUpdateIfNecessary: Unexpected batch number (current 1640, pending 1637)`

I think this is due to `this.props.readEndpoint` being defined in `app.jsx` and passed down to `navigation.jsx`, which then conflicts with the new `readEndpoint`. I can't avoid passing down the props because I'm using `{React.cloneElement(this.props.children, this.props)}` in `app.jsx` to make the API token available to all the components in the app.

I've also tried to use the classic `this.props.dispatch(...)` in `navigation.jsx` but the result is the same. It seems that once I add the API methods into `mapDispatchToProps`, the whole thing breaks.

Any suggestion regarding how could this approach be architected? Many thanks

**Comment by egeriis** [comment]
Isn't the idea with `mapDispatchToProps` that you don't need to call `dispatch`, but the actions are available directly as props? I.e. `this.props.actions()` instead of `this.props.dispatch(actions)`
