### ISSUE TITLE
Modify data received from API

### ISSUE THREAD

**Issue by gazpachu** [dixieio/redux-json-api#87]
I have a filters array that I receive from the API using the read method. With the UI, I can modify those filters and I would like to update the redux store. Is it possible to access the API reducer to add a custom method? what would be the best practice? Thanks

**Comment by egeriis** [comment]
I am not sure, if what you're asking is the ability to modify the `api` namespace in the Redux state? That would be bad practice, since that would counter the idea behind this library to provide a structured store of all your resources.

**Comment by gazpachu** [comment]
@egeriis I meant if I could modify the `filters` data that I got from the API using a custom reducer.

**Comment by egeriis** [comment]
Still not sure what you mean. What is "filters data" is it a collection of resources? And what do you need to modify?

**Comment by gazpachu** [comment]
@egeriis, sorry I didn't explain myself well. Let's try with the following flow of actions:

1. The app reads from the API a set of data. In this case, an array of objects
2. The data is added to redux
3. The UI in the app changes and I need to reflect that change into the same array of objects I received from the API
4. Can I modify it in any way? i.e. by creating a custom reducer? or is this not a good practise?

Thanks

**Comment by pannz** [comment]
after overview, In my understanding,  redux-json-api make request and then automatically return the response in `State`,  by something like state.set(`${type}`, data),  and then we can get data from `mapStateToProps`.   right?

And there is an case that many times the response data may not suitable for directly use, so we often modify the response using interceptor then return the preferred data construct,  or before render, in componentWillReceiveProps life-circle func to reconstruct data and then render, or some other methods to do that.
And now it looks like redux-json-api can't apply the former one (interceptor) but the later.  And obviously,  the form one is best practice. 
I think this is @gazpachu means

**Comment by egeriis** [comment]
@gazpachu _redux-json-api_ puts all your resources into `state.api` automatically. Through `mapStateToProps` you can read these resources into the component which should consume on it. Still not sure what you mean with modifying the data. But let me give an example.

Somewhere you're loading _users_ using `readEndpoint('users')`. The API responds with a resource collection of type "users", these will be put into `state.api.users`, e.g.:

```json
{
  "api": {
    "users": {
      "data": [
        { "type": "users", "id": 1, "attributes": { "name": "John Doe" } },
        { "type": "users", "id": 2, "attributes": { "name": "Jane Doe" } }
      ]
    }
  }
}
```

Then using `mapStateToProps` they can be "loaded" into your component:

```js
const mapStateToProps = ({ api: { users = { data: [] } }) => ({ users: users.data });
class MyComp extends Component {
  render() {
    return (
      <ul>
        {this.props.users.map(user => <li>{user.attributes.name}</li>)}
      </ul>
    );
  }
}

export default connect(mapStateToProps)(MyComp);
```

**Comment by gazpachu** [comment]
@egeriis let's use your example and hopefully I can make my point across.

The API responds with a resource collection of type "users", these will be put into state.api.users. OK! Now, imagine that I want to change some things in that collection of users and then send it back to the API. How can I do that? Which reducer should I use?

PS. I think I was failing to communicate what I wanted because I wasn't using the keywords "resource", "collection" and "type". Apologies for that.

**Comment by Nopzen** [comment]
@gazpachu - Do i understand you correctly you want to change the data recived from the API before it hits the `redux state`? Incase that would not be very nice and good practise to modify server data.

After the data have hit the state you can then modify it as you like in the view.

While mapping the data to the view through `mapStateToProps` you are then able to filter, sort, slice and what have you. To use @egeriis example.

In this case we want to only have users have and `ID`of `2`or more.

```js
const mapStateToProps = ({ 
  api: { 
    users = { data: [] 
  }
}) => ({ 
  users: users.data
    .filter(user => user.id >= 2)
});
class MyComp extends Component {
  render() {
    return (
      <ul>
        {this.props.users.map(user => <li>{user.attributes.name}</li>)}
      </ul>
    );
  }
}

export default connect(mapStateToProps)(MyComp);
```

The prop `users`is now an array that contains the `Jane Doe`.
See what we give you though this library as _one source of truth_ and this should't be tampered with, this is data stored in your database.

But what you do with the data while mapping it to props is your choice since you are not modifying the data. You could normalize data sets or filter and sort them from here.

If you want to do changes to the a user or a set of users you should dispatch the [updateEntity] (https://github.com/dixieio/redux-json-api/blob/master/docs/api.md#updateentity-resource-object--promise) for each resource/entity you would like to update.

I hope this de-mystify, all view / ui filters should be done while mapping the data to the props of the component, and all data changes should go through "official routes" such as `updateEntity`

**Comment by egeriis** [comment]
@gazpachu Sending changes back to the API, do you mean making a PATCH request to the API? In such case, @Nopzen is spot on in his mention of `updateEntity`.

**Comment by gazpachu** [comment]
@egeriis Thanks for all the explanation. This is just all I needed to hear:

> See what we give you though this library as one source of truth and this should't be tampered with, this is data stored in your database.

**Comment by Nopzen** [comment]
correct @gazpachu  - But you dont need to run `updateEntity` if its just the view that needs to either filter or sort the data, you do that through the `mapStateToProps` :)

**Comment by egeriis** [comment]
If you want to persist the changes your making to your dataset, you would need to use `updateEntity`, yes. `updateEntity` will keep your state _and_ API up-to-date.

If you do not want to persist the changed, but simply want to morph some values, you can do that in many different ways. E.g. through (reselect)[https://github.com/reactjs/reselect]:

```js
const getUsers = state => state.api.users;

const getUserAges = createSelector(
  getUsers,
  users => users.map(user => calculateAge(user.attributes.birthday))
);

const mapStateToProps = (state, props) => ({
  ages: getUserAges(state)
});
```

Just a dummy example :)

**Comment by egeriis** [comment]
Closed due to inactivity
