### ISSUE TITLE
Axios

### ISSUE THREAD

**Issue by Lavoaster** [dixieio/redux-json-api#9]
I'd like to suggest the use of [axios](https://github.com/mzabriskie/axios) over fetch. It has quite a few benefits over fetch.

- Global Auth (Meaning auth would not be a concern of this package, you'd pass through an axios client preconfigured for auth)
- Interceptors (For an example of why this is useful, I use OAuth for API authentication, so the client deals with hourly access_token refreshes, and needs to handle this transparently, an interceptor allows me to automatically catch 403's and refresh the access_token and re-fire the request with these. I don't have an example Axios implementation, but I do have one for Angular's $http [here](https://github.com/Poniverse/Poniverse.net/blob/master/src/client/app/blocks/recover-session/recover-session.js) which is very similar)
- Generally allows for much more control by the implementation of this package.
- `.then` and `.catch` are properly fired based on the response code, so no more manual status code checking.

If this would be something you're interested in, I'd be happy to fork and add it myself.

**Comment by Nopzen** [comment]
Hi @Lavoaster.

Thank you very much for you interest in Redux JSON API, i've taken a look and __axios__ and it looks like a nice addition to the tool.

We would __love__❤️ if you would like to create a fork, and write and implementation and submit a pull request to us and we will look it over as soon as we get it.

Make sure you are adding tests to the new implementation.

If you have any question feel free to ask.

Thank you very much for your time.

**Comment by egeriis** [comment]
@Lavoaster Did you have time to look into this proposal?

**Comment by Lavoaster** [comment]
@egeriis, I haven't yet. I'm currently on holiday so I won't be able to get on this until early next week.

**Comment by egeriis** [comment]
@Lavoaster That's perfect :)

**Comment by egeriis** [comment]
Hey @Lavoaster, do you need us to assist with this PR?

**Comment by Lavoaster** [comment]
Hey, I apologise about the lack of updates on my end. I intended to work on this when I came to refactoring a project at work to use this, however, that has been delayed. Consider this task "up for grabs" until I can finally get around this, so if anyone want to do this before I can feel free to do so. If it hasn't been done by the time I'm ready, I'll be able to do it. I don't want to block anything with people waiting for me to get something done.

**Comment by egeriis** [comment]
Great, thanks for the update. We'll have a look at it ourselves :)

**Comment by Lavoaster** [comment]
@egeriis Have you guys already started looking into this? I've just been given the go ahead at work to start on it.

**Comment by egeriis** [comment]
@Lavoaster We haven't had the time yet, unfortunately.

**Comment by Lavoaster** [comment]
@egeriis Ok, I'll start work on it then.

**Comment by Lavoaster** [comment]
@egeriis Why does the upload action append the access token as a parameter as apposed to the `Authorization` header? https://github.com/dixieio/redux-json-api/blob/master/src/jsonapi.js#L52

**Comment by egeriis** [comment]
Yeah, good question. The only reason is that the `uploadFile` method is legacy, and does not belong to this library. We intend to remove it, see #2, but haven't gotten to it yet. 
There are superior methods for uploading files, that adhere to the JSON API standard.

I suggest to either a) remove this method in your branch or b) update it to use Axios and allow us to remove it in another PR.

**Comment by Lavoaster** [comment]
@egeriis Do you guys do manual integration testing via another project using `npm link` and webpack with this package? If so, how does that work for you?

**Comment by egeriis** [comment]
No, we do not do that at the moment. It's one of the think we'd love to improve. Automatic integration tests or something semi-automatic like using `npm link`. 

It would be great if we could simulate API calls in unit tests also.

**Comment by egeriis** [comment]
We've been using `npm link` for the latest PR, #21, and it's working great for us.

**Comment by Lavoaster** [comment]
Ah, It hasn't been behaving for me. I guess it's a local webpack config issue with my project. For now I've been testing via installing directly via my github repo.

**Comment by egeriis** [comment]
How is this feature going along @Lavoaster? :)

**Comment by Lavoaster** [comment]
Ah, you can see the initial commit of this 13 days ago, and as of right now nothing has changed. Last I played with this, I will be getting back on it soon, I was having trouble with axios and sending it the authentication header. 

I'm not 100% sure if axios configuration should be managed through the redux store. As apposed to calling a method in this library to pass it a pre-configured axios instance. Any thoughts?

**Comment by egeriis** [comment]
I've given this some thought, because I've used numbro and moment in some of our applications. And they also have some global configuration. For now I've bootstrapped that in my root view on `componentWillMount`. But tying it up to the redux store could make sense, if that's somewhat easily achievable. Not sure where to dispatch the actions that set the configuration though, might be a layer that is not necessary.
Do you have an idea on how this could be done?

**Comment by egeriis** [comment]
Closing as there is now a PR #29
