### ISSUE TITLE
Bug in v1.6.1: redux adding up new values into resource on each readEndpoint call

### ISSUE THREAD

**Issue by gazpachu** [dixieio/redux-json-api#96]
This is the sequence to replicate the issue:

Load endpointA with queryString Q = 1:
- Resource R receives 2 items of type T)
- Redux displays 2 items in resource R

Load endpointA with queryString Q = 2:
- Resource R receives 1 item of type T)
- Redux displays 3 items in resource R (it should display just one...)

Load endpointA with queryString Q = 1:
- Resource R receives 2 items of type T)
- Redux displays 5 items in resource R (it should display just two...)

<img style="width: 100%" width="295" alt="screen shot 2016-11-22 at 14 26 08" src="https://cloud.githubusercontent.com/assets/1721288/20525469/eb6d93c4-b0bf-11e6-8981-56712ba21022.png">
<img style="display: block" width="294" alt="screen shot 2016-11-22 at 14 26 45" src="https://cloud.githubusercontent.com/assets/1721288/20525468/eb6d60de-b0bf-11e6-987d-a64c902d169e.png">
<img style="display: block" width="297" alt="screen shot 2016-11-22 at 14 32 16" src="https://cloud.githubusercontent.com/assets/1721288/20525545/40296f96-b0c0-11e6-86d5-ecee21ff5569.png">

**Comment by egeriis** [comment]
This is by design.

There's a discussion here in this thread, with regards to the ability to clear resource types from state upon new successful request: #24
