### ISSUE TITLE
Update entity fails if not performed other operation to the endpoint before

### ISSUE THREAD

**Issue by danielgefen** [dixieio/redux-json-api#98]
I'm trying to call the function `updateEntity` and I'm getting this error:
`Uncaught TypeError: Cannot read property 'update' of undefined`
happening in this line:

![screen shot 2016-12-06 at 15 24 15](https://cloud.githubusercontent.com/assets/15183805/20926989/194781fc-bbc8-11e6-9a4a-b20e2f1b789c.png)

I found out that since I'm calling `updateEntity` on this endpoint api before calling any other operation such as `readEndpoint` or `createEntity`, the endpoint api name (which is also the entities type) is not a property in the state of redux-json-api, and that's why I am receiving the `undefined` error.

For example, if I'm calling `readEndpoint` before calling `updateEntity`, everything works fine, since the endpoint api name (entities type) is added as a property to the state.

In my case, it's unnecessary to call `readEndpoint`first, since I already have all the necessary data for updating the entity. 

I would like to be able to call `updateEntity` without assuming other operations were called before.

**Comment by egeriis** [comment]
@danielgefen Wow, good catch! Are you willing to do a PR?
Also I am very curious about your use case. How do you know about an entity if you haven't loaded it? 🙂

**Comment by danielgefen** [comment]
Yes, I'll try to do a PR. Hopefully I will manage to resolve this issue :)

I guess my case is kinda special. Since in our backend, I have an endpoint api which returns an entity that contains an array of entities data from a different endpoint api. We chose not to return a relationship in this case since the structure and the usage is a bit more complex than this, and actually doing it like this is making our lives easier and improving performance for us.
