### ISSUE TITLE
Docs are missing a working example

### ISSUE THREAD

**Issue by tomharvey** [dixieio/redux-json-api#99]
I spent some time earlier today in trying to get to know how to add this library. I noticed that there were 2 issues ( https://github.com/dixieio/redux-json-api/issues/13 and https://github.com/dixieio/redux-json-api/issues/44 ) where people have had similar problems so I've documented my work in the README of my experimentation repo https://github.com/tomharvey/redux-json-api-demo/

I appreciate that the issues were closed as they were worked around, but if you feel that the README is valuable I'd love to hear feedback on how to best implement for others.

Also - if I've made any glaring errors in my implementation that would be great to hear feedback on too.

Thanks for an otherwise awesome package.

**Comment by egeriis** [comment]
This is great, @tomharvey. We'd be happy to link to your repo in the README. While another contributor has been working on #72, it hasn't been wrapped up and I think it makes sense to have a dedicated "demo" repo. 

Maybe you'll find some inspiration in that PR as well?

**Comment by tomharvey** [comment]
Ah yes, I meant to link to https://github.com/dixieio/redux-json-api/pull/72 in my issue report as well.

I see that @Nopzen has been working on that but a fully functioning sandpit to play with the API is somewhat more work than a simple quickstart and I can understand that it might take him a while to complete this.

I can raise a PR with the link as a "Quickstart Guide". Any feed back on how I've implemented it in my repo; I want to keep the implementation clear and simple to follow but I don't want to encourage any bad patterns of use.

**Comment by tomharvey** [comment]
Excellent point, well made. Thanks
